# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip: "192.168.10.200"
    db.vm.provision "shell", path: "environment/db/provision.sh"
end
  
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.network "private_network", ip: "192.168.10.100"
    app.hostsupdater.aliases = ["development.local"]
    app.vm.synced_folder "app", "/home/ubuntu/app"
    app.vm.provision "shell", path: "environment/app/provision.sh", privileged: false
  end
end
# # file sets up mongodb and app
# # updates should merge to master through jenkins
# <<<<<<< HEAD
# <<<<<<< HEAD
# # testing, testing, testing, testing, testing, arbrawf, arbrofi
# =======
# # testing, testing, testing, testing, arbrofi...
# >>>>>>> dev
# =======
# # testing, testing, testing, testing, arbrofi...
# =======
# # testing, testing, testing, testing, testing, testing...
# >>>>>>> master
# >>>>>>> a7b92ff09bd38da47ff6cbbfec65230a96102001
# testing, testing, testing, testing, testing, should work
